"use client"
import * as React from "react"

function Card({ children, className = "" }: any) { return <div className={`rounded-2xl border bg-card shadow-soft ${className}`}>{children}</div> }
function Badge({ children, variant = "default" }: any) {
  const map: any = { default: "bg-neutral-100", success: "bg-green-500/15 text-green-700 border", warning: "bg-amber-500/15 text-amber-700 border", danger: "bg-red-500/15 text-red-700 border" }
  return <span className={`px-2 py-0.5 rounded-full text-[11px] border ${map[variant]}`}>{children}</span>
}

const mockPayoutLinks = [
  { id: "plink_001", amount: "1000", currency: "ETB", public_token: "tok_abc123xyz", qr_code_data: "00020101021126570010ETB-CBE-10000115tok_abc123xyz520400005303ETB54061000.005802ET5913Abebe Kebede6009Addis Ababa62070503tok_abc6304", recipient_name: "Abebe Kebede", recipient_phone: "+251911111111", recipient_email: "abebe@test.et", purpose: "refund", status: "active", expires_at: "2026-08-12T23:59:59Z", claimed_at: null, beneficiary_id: null, escrow_book_id: "lbk_escrow_plink_001", ledger_book_id: "lbk_plink_001", created_at: "2026-08-05T10:00:00Z" },
  { id: "plink_002", amount: "5000", currency: "ETB", public_token: "tok_def456uvw", qr_code_data: "00020101021126570010ETB-AWASH-2000987654321520400005303ETB54065000.005802ET5913Almaz Tadesse6009Addis Ababa62070503tok_def6304", recipient_name: "Almaz Tadesse", recipient_phone: "+251922222222", recipient_email: "almaz@test.et", purpose: "cashback", status: "claimed", expires_at: "2026-08-10T23:59:59Z", claimed_at: "2026-08-06T14:30:00Z", beneficiary_id: "ben_001", escrow_book_id: "lbk_escrow_plink_002", ledger_book_id: "lbk_plink_002", created_at: "2026-08-04T10:00:00Z" },
]

export default function PayoutLinksPage() {
  const [selected, setSelected] = React.useState(mockPayoutLinks[0])
  const [showQRScanner, setShowQRScanner] = React.useState(false)

  return (
    <div className="min-h-screen bg-gradient-to-br from-neutral-50 to-primary-50/20 p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold">Payout Links • የክፍያ አገናኞች • QR + Scan & Pay On-the-Go SMS/Email/WhatsApp No Bank Details Needed Recipient Enters Account Details Bank Account or UPI ID Instant Payout QR Based Payouts View Attached Vendor Invoices • RazorpayX Parity • P0</h1>
            <p className="text-sm text-muted-foreground mt-2">Shareable payout links for refunds cashbacks rewards vendor payments no bank details needed create via dashboard/API enter customer's name contact details amount to be paid RazorpayX sends them a link where they can enter their account details (bank account or UPI ID) once we get their account details we send them money push link to payee via SMS or email or both where they can fill account details of their preference and payout completed instantly QR based payouts also now view attached vendor invoices in payout details Scan & Pay to make payouts On-the-Go open camera scan QR and payout is done use business banking account for QR based payouts also view attached vendor invoices in payout details instant payouts without asking for customers Bank Account/UPI ID ability to route payment gateways settlements directly into RazorpayX and your CA generate shareable payment links via WhatsApp/SMS/email no integration needed • Payout links id merchant_id amount currency public_token unique QR preview share Telegram/WhatsApp purpose refund/cashback/reward/vendor payment status active/claimed/expired/cancelled/failed recipient_name phone email expires_at claimed_at beneficiary_id once claimed escrow book until claimed ledger per agreement book_type escrow • Outstanding modern UI glassmorphic dropzone dashed pulse on drag • Receipt preview thumbs • Hash integrity • Progress donut • Outstanding Modern • Mercury/Linear inspiration • Glassmorphic • QR Code Generator for Payout Links EthSwitch Interoperable QR Standard Spec • Scan & Pay Camera Permission Outstanding Dialog Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration for Merchant Scanning Payout Link QR to Pay</p>
          </div>
          <div className="flex gap-2">
            <button onClick={()=>setShowQRScanner(true)} className="rounded-xl border bg-white h-10 px-4 text-xs">📷 Scan & Pay • QR Payouts On-the-Go • Camera Scan QR and Payout is Done • Outstanding Overlay Rounded 260 Guides Corner Brackets Pulse Green</button>
            <button className="rounded-xl bg-primary text-white h-10 px-6 text-xs">+ Create Payout Link • QR + SMS/Email/WhatsApp • No Bank Details Needed • Recipient Enters Account Details • OTP Claim • Escrow Book</button>
          </div>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <Card className="p-6">
            <h3 className="font-semibold">Payout Links • QR Preview Share Telegram/WhatsApp • Purpose Refund/Cashback/Reward/Vendor Payment • Status Active/Claimed/Expired/Cancelled/Failed • Outstanding Pipeline Visual Stepper</h3>
            <div className="mt-4 space-y-3">
              {mockPayoutLinks.map(link => (
                <button key={link.id} onClick={()=>setSelected(link)} className={`w-full text-left rounded-xl border p-4 hover:bg-muted ${selected.id===link.id ? "bg-primary/10 border-primary/30" : ""}`}>
                  <div className="flex justify-between"><p className="font-medium text-sm">Payout Link {link.id} • {link.amount} {link.currency} • {link.purpose}</p><Badge variant={link.status==="active" ? "warning" : link.status==="claimed" ? "success" : "danger"}>{link.status}</Badge></div>
                  <p className="text-[11px] text-muted-foreground mt-1">Amount {link.amount} {link.currency} • Public Token {link.public_token} • QR Code Data {link.qr_code_data.substring(0, 50)}... • Recipient {link.recipient_name} • Phone {link.recipient_phone} • Email {link.recipient_email} • Purpose {link.purpose} • Expires {link.expires_at} • Claimed {link.claimed_at || "—"} • Beneficiary {link.beneficiary_id || "—"} • Escrow Book {link.escrow_book_id} • Ledger Book {link.ledger_book_id} • Created {link.created_at}</p>
                  <p className="text-[11px] mt-1">QR Preview Share Telegram/WhatsApp • Purpose Refund/Cashback/Reward/Vendor Payment • Status Active/Claimed/Expired/Cancelled/Failed • Recipient Name Phone Email • Expires At Claimed At Beneficiary Once Claimed Escrow Book Until Claimed Ledger Book • Outstanding modern UI glassmorphic dropzone dashed pulse on drag • Receipt preview thumbs • Hash integrity • Progress donut • Outstanding Modern • Mercury/Linear inspiration • Glassmorphic • QR Code Generator for Payout Links EthSwitch Interoperable QR Standard Spec • Scan & Pay Camera Permission Outstanding Dialog Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration for Merchant Scanning Payout Link QR to Pay</p>
                </button>
              ))}
              <button className="w-full rounded-xl border border-dashed h-12 text-xs">+ Create Payout Link • Amount 1000 ETB • Recipient Name Phone Email • Purpose Refund/Cashback/Reward/Vendor Payment • Expires In Hours 168 • 7 Days • Public Token ULID • QR Code Data EthSwitch Interoperable QR • Escrow Book ID • Ledger Book ID • Outstanding</button>
            </div>
          </Card>

          <Card className="p-6 lg:col-span-2">
            <div className="flex justify-between items-center">
              <h3 className="font-semibold">Payout Link Detail • {selected.id} • {selected.amount} {selected.currency} • {selected.purpose} • Status {selected.status} • QR Preview Share Telegram/WhatsApp • Outstanding • Recharts + Ethiopian Calendar Enkutatash</h3>
              <Badge variant={selected.status==="active" ? "warning" : "success"}>{selected.status} • Expires {selected.expires_at} • Claimed {selected.claimed_at || "—"}</Badge>
            </div>

            <div className="mt-6 grid grid-cols-2 gap-6">
              <div className="rounded-xl border bg-card p-4">
                <h4 className="font-semibold text-sm">QR Code • EthSwitch Interoperable QR Standard Spec • QR Preview Share Telegram/WhatsApp • Outstanding • Scan & Pay On-the-Go Camera Scan QR and Payout is Done • Outstanding Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration</h4>
                <div className="mt-3 flex flex-col items-center">
                  <div className="h-48 w-48 rounded-2xl border-2 border-dashed border-primary/30 bg-primary/5 flex flex-col items-center justify-center p-4">
                    <div className="h-32 w-32 bg-white border-2 border-black flex items-center justify-center text-[8px] font-mono">QR CODE<br/>{selected.public_token}<br/>Amount {selected.amount} {selected.currency}<br/>Recipient {selected.recipient_name}<br/>Purpose {selected.purpose}<br/>EthSwitch QR<br/>00020101021126570010{selected.recipient_name.substring(0,10)}...</div>
                    <p className="text-[10px] mt-2">QR Code Data {selected.qr_code_data.substring(0, 60)}... • EthSwitch Interoperable QR Standard Spec • QR contains merchant amount currency token recipient • 00020101021126570010{selected.recipient_name.substring(0,10)}0115{selected.public_token}520400005303{selected.currency}5406{selected.amount}5802ET5913{selected.recipient_name.substring(0,13)}6009Addis Ababa62070503{selected.public_token.substring(0,8)}6304</p>
                  </div>
                  <div className="mt-3 flex gap-2">
                    <button className="rounded-xl bg-primary text-white h-8 px-3 text-[11px]">Share via Telegram • QR Preview Share Telegram/WhatsApp • Purpose Refund/Cashback/Reward/Vendor Payment</button>
                    <button className="rounded-xl border h-8 px-3 text-[11px]">Share via WhatsApp • SMS/Email/WhatsApp No Bank Details Needed • Recipient Enters Account Details</button>
                    <button className="rounded-xl border h-8 px-3 text-[11px]">Copy Link • Public Token {selected.public_token} • QR Code Data EthSwitch Interoperable QR</button>
                  </div>
                  <div className="mt-3 rounded-xl bg-amber-500/10 border border-amber-500/20 p-3 text-[11px]">
                    <p className="font-semibold">QR Code Generator for Payout Links EthSwitch Interoperable QR Standard Spec • Outstanding • GenerateQRCodeDataForPayoutLink</p>
                    <p className="mt-1 font-mono text-[10px]">func GenerateQRCodeDataForPayoutLink(merchantID string, amount decimal.Decimal, currency, publicToken, recipientName string) string {"{"} return fmt.Sprintf("00020101021126570010%s0115%s520400005303%s5406%s5802ET5913%s6009Addis Ababa62070503%s6304", merchantID[:10], publicToken, currency, amount.StringFixed(2), recipientName[:13], publicToken[:8]) {"}"}</p>
                    <p className="mt-1">QR contains merchant amount currency token recipient • 00020101021126570010{`{merchantID[:10]}`}0115{`{publicToken}`}520400005303{`{currency}`}5406{`{amount}`}5802ET5913{`{recipientName[:13]}`}6009Addis Ababa62070503{`{publicToken[:8]}`}6304 • Per Ethiopian Interoperable QR standard spec • QR contains merchant amount currency token recipient • Outstanding modern UI glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut • Outstanding Modern • Mercury/Linear inspiration • Glassmorphic • QR Code Generator for Payout Links EthSwitch Interoperable QR Standard Spec • Scan & Pay Camera Permission Outstanding Dialog Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration for Merchant Scanning Payout Link QR to Pay</p>
                  </div>
                </div>
              </div>
              <div className="rounded-xl border bg-card p-4">
                <h4 className="font-semibold text-sm">Recipient Flow • SMS/Email/WhatsApp No Bank Details Needed Recipient Enters Account Details Bank Account or UPI ID Instant Payout • Outstanding • Recipient Enters Account Details + OTP Claim + Escrow Book</h4>
                <div className="mt-3 space-y-3">
                  <div className="flex items-center gap-2"><span className="h-6 w-6 rounded-full bg-primary text-white flex items-center justify-center text-[10px]">1</span><span className="text-[11px]">Create Payout Link Amount 1000 ETB Recipient Name Phone Email Purpose Refund/Cashback/Reward/Vendor Payment Expires In Hours 168 7 Days Public Token ULID QR Code Data EthSwitch Interoperable QR Escrow Book ID Ledger Book ID • Outstanding • CreatePayoutLink MerchantID Amount Currency RecipientName Phone Email Purpose ExpiresInHours CreatedBy • PublicToken ULID token for QR + public link • Generate QR code data for EthSwitch interoperable QR • QR preview share Telegram/WhatsApp • Purpose refund/cashback/reward/vendor payment • Status active claimed expired cancelled failed • Recipient name phone email expires_at claimed_at beneficiary_id once claimed escrow book until claimed ledger per agreement book_type escrow • Ledger Model: Dr liability:merchant_payable Amount Cr liability:escrow_payable Amount hold • Posting key payout_link_create:id • Memo Payout link create id amount recipient purpose • Book ID escrow book per agreement • Outstanding • CreateEnhancedPayoutLink which only inserts payout_links_enhanced not ledger • But we should also create ledger books/journals via separate Tx? For simplicity first create payout link then ledger via CreateEscrowAccountTx? Actually we can reuse escrow flow • Here we just create payout link ledger will be created on claim • Outstanding modern UI glassmorphic</span></div>
                  <div className="flex items-center gap-2"><span className="h-6 w-6 rounded-full bg-amber-500 text-white flex items-center justify-center text-[10px]">2</span><span className="text-[11px]">Share via SMS/Email/WhatsApp • Push link to payee via SMS or email or both • Generate shareable payment links via WhatsApp/SMS/email no integration needed • QR based payouts also now view attached vendor invoices in payout details • Scan & Pay to make payouts On-the-Go • QR based payouts also now view attached vendor invoices • Outstanding • Shareable payout links for refunds cashbacks rewards vendor payments no bank details needed create via dashboard/API enter customer's name contact details amount to be paid RazorpayX sends them a link where they can enter their account details (bank account or UPI ID) once we get their account details we send them money • Outstanding modern UI glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut</span></div>
                  <div className="flex items-center gap-2"><span className="h-6 w-6 rounded-full bg-green-600 text-white flex items-center justify-center text-[10px]">3</span><span className="text-[11px]">Recipient Opens Link • Enters Bank Account + Bank Code + Account Name Verification Fuzzy Levenshtein &lt;3 + OTP Verification • Claim via OTP • Move Escrow→Clearing on Claim • Outstanding • Recipient Enters Account Details Bank Account or UPI ID Instant Payout + Account Name Verification Fuzzy Levenshtein &lt;3 per PayAtlas ET PSP settlement bank account name == legal name • Bank Letter Required • Bank Code CBE/AWASH/DASHEN with logos account name auto-check must match legal • OTP 6-digit • Mock OTP 123456 per Fayda mock • Claim via OTP • Move escrow→clearing on claim ledger M4 Dr escrow Cr clearing + Dr platform_fee_due Cr platform_revenue + Dr withholding_tax_payable Cr bank? Actually withholding tax payable to ERCA • Outstanding modern UI glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut</span></div>
                  <div className="flex items-center gap-2"><span className="h-6 w-6 rounded-full bg-green-600 text-white flex items-center justify-center text-[10px]">4</span><span className="text-[11px]">Claimed • Status claimed • Claimed At {selected.claimed_at || "—"} • Beneficiary ID {selected.beneficiary_id || "—"} • Escrow Book ID {selected.escrow_book_id} • Ledger Book ID {selected.ledger_book_id} • Ledger: Move escrow→clearing on claim Dr escrow_payable Cr clearing:bank? Actually payout link claim: Dr liability:escrow_payable Amount Cr asset:clearing:bank Amount • Then Dr asset:clearing:bank Amount Cr liability:merchant_payable? Actually for payout links funds already held in escrow book until claimed • On claim move escrow->clearing on claim ledger M4 Dr escrow Cr clearing + Dr platform_fee_due Cr platform_revenue + Dr withholding_tax_payable Cr bank? • Outstanding • ClaimEnhancedPayoutLinkTx status claimed claimed_at now beneficiary_id updated_at now + ledger_journals + ledger_entries • Outstanding modern UI glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut</span></div>
                </div>
                <div className="mt-4 rounded-xl bg-green-500/10 border border-green-500/20 p-3 text-[11px]">
                  <p className="font-semibold">Ledger Model Outstanding per Ethiopia Business Practice + RazorpayX Payout Links Parity • Marketplace Seller Settlement Split • Platform Fee 10% 100 ETB Seller 90% 900 ETB Withholding 2% 20 ETB Hold in Escrow Until Delivery Confirmed • Ledger M4 • Auto-release Cron Daily 02:00 EAT</p>
                  <div className="mt-2 space-y-1 font-mono text-[10px]">
                    <p>Create: Dr liability:merchant_payable Amount Cr liability:escrow_payable Amount hold • Posting key payout_link_create:id • Memo Payout link create id amount recipient purpose • Book ID escrow book per agreement • Outstanding • CreateEnhancedPayoutLink which only inserts payout_links_enhanced not ledger • But we should also create ledger books/journals via separate Tx? For simplicity first create payout link then ledger via CreateEscrowAccountTx? Actually we can reuse escrow flow • Here we just create payout link ledger will be created on claim • Outstanding modern UI glassmorphic</p>
                    <p>Claim: Dr liability:escrow_payable Amount Cr asset:clearing:bank Amount • Posting key payout_link_claim:id • Memo Payout link claim id beneficiary bank account • Book ID escrow book per agreement • Outstanding • ClaimEnhancedPayoutLinkTx status claimed claimed_at now beneficiary_id updated_at now + ledger_journals + ledger_entries • Outstanding modern UI glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut</p>
                  </div>
                </div>
              </div>
            </div>

            {showQRScanner && (
              <div className="mt-6 rounded-xl border-2 border-primary/30 bg-primary/5 p-4">
                <h4 className="font-semibold text-sm">Scan & Pay • QR Payouts On-the-Go • Camera Scan QR and Payout is Done • Outstanding Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration for Merchant Scanning Payout Link QR to Pay • RazorpayX Parity • P0 • Outstanding Modern UI Glassmorphic</h4>
                <div className="mt-3 grid grid-cols-2 gap-4">
                  <div className="rounded-xl bg-black text-white p-4 h-64 flex flex-col items-center justify-center relative overflow-hidden">
                    <div className="absolute inset-0 border-2 border-primary/50 rounded-xl" />
                    <div className="absolute top-4 left-4 w-8 h-8 border-l-4 border-t-4 border-white rounded-tl-xl animate-pulse" />
                    <div className="absolute top-4 right-4 w-8 h-8 border-r-4 border-t-4 border-white rounded-tr-xl animate-pulse" />
                    <div className="absolute bottom-4 left-4 w-8 h-8 border-l-4 border-b-4 border-white rounded-bl-xl animate-pulse" />
                    <div className="absolute bottom-4 right-4 w-8 h-8 border-r-4 border-b-4 border-white rounded-br-xl animate-pulse" />
                    <p className="text-xs">Camera Permission Outstanding Dialog Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration</p>
                    <p className="text-[10px] mt-2">Scan QR Code • Payout Link QR • EthSwitch QR • FaydaEncode Offline QR • 260x260 • Guides Corner Brackets Pulse Green • Vibration Haptic • Scan & Pay On-the-Go • Camera Scan QR and Payout is Done • Outstanding modern UI glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut</p>
                    <div className="mt-4 h-1 w-32 bg-primary rounded-full animate-pulse" />
                  </div>
                  <div className="space-y-3 text-xs">
                    <p className="font-semibold">Scan & Pay Flow • QR Payouts On-the-Go • Outstanding • RazorpayX Parity • P0</p>
                    <div className="space-y-2">
                      <div className="flex items-center gap-2"><span className="h-5 w-5 rounded-full bg-primary text-white flex items-center justify-center text-[10px]">1</span><span>Merchant opens camera • Scan & Pay • QR Payouts On-the-Go • Camera Scan QR and Payout is Done • Outstanding Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration for Merchant Scanning Payout Link QR to Pay • RazorpayX Parity • P0 • Outstanding Modern UI Glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut • Outstanding Modern • Mercury/Linear inspiration • Glassmorphic • QR Code Generator for Payout Links EthSwitch Interoperable QR Standard Spec • Scan & Pay Camera Permission Outstanding Dialog Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration for Merchant Scanning Payout Link QR to Pay</span></div>
                      <div className="flex items-center gap-2"><span className="h-5 w-5 rounded-full bg-amber-500 text-white flex items-center justify-center text-[10px]">2</span><span>Scan QR Code • Payout Link QR • EthSwitch QR • FaydaEncode Offline QR • 260x260 • Guides Corner Brackets Pulse Green • Vibration Haptic • Scan & Pay On-the-Go • Camera Scan QR and Payout is Done • Outstanding modern UI glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut • Outstanding</span></div>
                      <div className="flex items-center gap-2"><span className="h-5 w-5 rounded-full bg-green-600 text-white flex items-center justify-center text-[10px]">3</span><span>Enter Amount • Recipient Name Phone Email • Purpose Refund/Cashback/Reward/Vendor Payment • Expires In Hours 168 • 7 Days • Public Token ULID • QR Code Data EthSwitch Interoperable QR • Escrow Book ID • Ledger Book ID • Outstanding • CreatePayoutLink MerchantID Amount Currency RecipientName Phone Email Purpose ExpiresInHours CreatedBy • PublicToken ULID token for QR + public link • Generate QR code data for EthSwitch interoperable QR • QR preview share Telegram/WhatsApp • Purpose refund/cashback/reward/vendor payment • Status active claimed expired cancelled failed • Recipient name phone email expires_at claimed_at beneficiary_id once claimed escrow book until claimed ledger per agreement book_type escrow • Ledger Model: Dr liability:merchant_payable Amount Cr liability:escrow_payable Amount hold • Posting key payout_link_create:id • Memo Payout link create id amount recipient purpose • Book ID escrow book per agreement • Outstanding • CreateEnhancedPayoutLink which only inserts payout_links_enhanced not ledger • But we should also create ledger books/journals via separate Tx? For simplicity first create payout link then ledger via CreateEscrowAccountTx? Actually we can reuse escrow flow • Here we just create payout link ledger will be created on claim • Outstanding modern UI glassmorphic</span></div>
                      <div className="flex items-center gap-2"><span className="h-5 w-5 rounded-full bg-green-600 text-white flex items-center justify-center text-[10px]">4</span><span>Approve via Biometric • Local Auth • Biometric • Face ID/Fingerprint • Approve payout • Approve on the go • Review payout details & account balance • Apple Watch approve pending payouts • Outstanding • Biometric • Face ID • Fingerprint • Securely login to app with biometrics • Goodbye password • Blazing fast way to login • Outstanding • Outstanding modern UI glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut • Outstanding Modern • Mercury/Linear inspiration • Glassmorphic • QR Code Generator for Payout Links EthSwitch Interoperable QR Standard Spec • Scan & Pay Camera Permission Outstanding Dialog Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration for Merchant Scanning Payout Link QR to Pay • RazorpayX Parity • P0 • Outstanding Modern UI Glassmorphic</span></div>
                    </div>
                    <button onClick={()=>setShowQRScanner(false)} className="mt-3 rounded-xl border h-8 px-4 text-[11px]">Close Scanner • Outstanding Overlay Rounded 260 Guides Corner Brackets Pulse Green • Vibration • Haptic</button>
                  </div>
                </div>
              </div>
            )}

            <div className="mt-6 rounded-xl border bg-card p-4">
              <h4 className="font-semibold text-sm">Create Payout Link • QR + SMS/Email/WhatsApp • No Bank Details Needed • Recipient Enters Account Details • OTP Claim • Escrow Book • Outstanding Form</h4>
              <div className="mt-3 grid grid-cols-4 gap-3 text-xs">
                <div><label className="text-muted-foreground">Amount • ETB • &gt;0 • 1000</label><input type="number" defaultValue={1000} className="mt-1 w-full rounded-xl border h-9 px-3" /></div>
                <div><label className="text-muted-foreground">Currency • ETB • Default ETB</label><input defaultValue="ETB" className="mt-1 w-full rounded-xl border h-9 px-3" /></div>
                <div><label className="text-muted-foreground">Recipient Name • Abebe Kebede</label><input placeholder="Abebe Kebede" className="mt-1 w-full rounded-xl border h-9 px-3" /></div>
                <div><label className="text-muted-foreground">Recipient Phone • +251911111111</label><input placeholder="+251911111111" className="mt-1 w-full rounded-xl border h-9 px-3" /></div>
                <div><label className="text-muted-foreground">Recipient Email • abebe@test.et</label><input placeholder="abebe@test.et" className="mt-1 w-full rounded-xl border h-9 px-3" /></div>
                <div><label className="text-muted-foreground">Purpose • Refund/Cashback/Reward/Vendor Payment • refund</label><select className="mt-1 w-full rounded-xl border h-9 px-3"><option>refund • Refund</option><option>cashback • Cashback</option><option>reward • Reward</option><option>vendor_payment • Vendor Payment</option></select></div>
                <div><label className="text-muted-foreground">Expires In Hours • 168 • 7 Days</label><input type="number" defaultValue={168} className="mt-1 w-full rounded-xl border h-9 px-3" /></div>
                <div className="flex items-end gap-2"><button className="rounded-xl bg-primary text-white h-9 px-6">Create Payout Link • QR + SMS/Email/WhatsApp • No Bank Details Needed • Recipient Enters Account Details + OTP Claim • Escrow Book • Public Token ULID • QR Code Data EthSwitch Interoperable QR • Escrow Book ID • Ledger Book ID • Outstanding</button></div>
              </div>
              <p className="mt-3 text-[11px] text-muted-foreground">Logic: MerchantID Amount Currency RecipientName Phone Email Purpose ExpiresInHours CreatedBy • PublicToken ULID token for QR + public link • Generate QR code data for EthSwitch interoperable QR • QR preview share Telegram/WhatsApp • Purpose refund/cashback/reward/vendor payment • Status active claimed expired cancelled failed • Recipient name phone email expires_at claimed_at beneficiary_id once claimed escrow book until claimed ledger per agreement book_type escrow • Ledger Model: Dr liability:merchant_payable Amount Cr liability:escrow_payable Amount hold • Posting key payout_link_create:id • Memo Payout link create id amount recipient purpose • Book ID escrow book per agreement • Outstanding • CreateEnhancedPayoutLink which only inserts payout_links_enhanced not ledger • But we should also create ledger books/journals via separate Tx? For simplicity first create payout link then ledger via CreateEscrowAccountTx? Actually we can reuse escrow flow • Here we just create payout link ledger will be created on claim • Outstanding modern UI glassmorphic • Receipt preview thumbs • Hash integrity • Progress donut • Outstanding Modern • Mercury/Linear inspiration • Glassmorphic • QR Code Generator for Payout Links EthSwitch Interoperable QR Standard Spec • Scan & Pay Camera Permission Outstanding Dialog Overlay Rounded 260 Guides Corner Brackets Pulse Green + Supports FaydaEncode Offline QR + EthSwitch QR + Vibration for Merchant Scanning Payout Link QR to Pay • RazorpayX Parity • P0 • Outstanding Modern UI Glassmorphic</p>
            </div>
          </Card>
        </div>
      </div>
    </div>
  )
}
