"use client"
import * as React from "react"

function Card({ children, className = "" }: any) { return <div className={`rounded-2xl border bg-card shadow-soft ${className}`}>{children}</div> }
function Badge({ children, variant = "default" }: any) {
  const map: any = { default: "bg-neutral-100", success: "bg-green-500/15 text-green-700 border", warning: "bg-amber-500/15 text-amber-700 border", danger: "bg-red-500/15 text-red-700 border" }
  return <span className={`px-2 py-0.5 rounded-full text-[11px] border ${map[variant]}`}>{children}</span>
}

const mockTickets = [
  { id: "tick_001", merchant_id: "mer_01H", user_id: "user_001", subject: "Payout batch pbat_001 pending approval >50k threshold • Maker-checker dual approval not working", description: "Payout batch pbat_001 with 50,000 payouts amount 5000000 ETB requires approval per maker-checker dual approval >50k payout >100k payroll approval count approver != submitter onboarding dual approval risk>=70 or TPV>1M but approval workflow builder not showing approval ranges", priority: "high", status: "open", assigned_to: "rm_001", sla_due_at: "2026-08-06T10:00:00Z", resolved_at: null, created_at: "2026-08-05T10:00:00Z" },
  { id: "tick_002", merchant_id: "mer_01H", user_id: "user_002", subject: "Bank account verification penny testing 1 ETB failed for CBE ****1234 • Account name mismatch Levenshtein 3", description: "Bank account verification penny testing 1 ETB deposit single rupee returns validated bank details + beneficiary name fund account validation is service provided by Razorpay which can be used to verify authenticity of end beneficiary's bank account or UPI ID achieved by depositing single rupee into intended account which returns validated bank details along with beneficiary's name of account number provided by end beneficiary • Account name Apex Trading PLC but beneficiary returned Abebe Kebede mismatch Levenshtein distance 8 >3 per PayAtlas ET PSP settlement bank account name == legal name • Bank Letter Required", priority: "medium", status: "in_progress", assigned_to: "rm_001", sla_due_at: "2026-08-07T10:00:00Z", resolved_at: null, created_at: "2026-08-05T09:00:00Z" },
  { id: "tick_003", merchant_id: "mer_01H", user_id: "user_003", subject: "Payroll run July2026_Regular total_gross 200k net 150k tax 20k pension 14k/22k employer cost 222k variance +5.2% vs Jun • Ledger M4 balanced? • ValidateBalanced O(n) • Advisory lock pg_advisory_xact_lock(hashtext(book_id)) • Upsert balances O(1) PK • No float money • Decimal precise", description: "Payroll run July2026_Regular total_gross 200k net 150k tax 20k pension 14k/22k employer cost 222k variance +5.2% vs Jun • Ledger M4 per run book Dr expense:salary totalGross Cr payroll_payable totalNet Cr et_income_tax_payable totalTax Cr pension_payable totalPension balanced ValidateBalanced sum debits==credits O(n) PostJournalTx advisory lock pg_advisory_xact_lock(hashtext(book_id)) atomic journal+entries+balances upsert PK O(1) GetBalance PK O(1) ListJournalsByRef ref index tests TestValidateBalanced M1-M4 property 10k iterations deterministic seed 42 + TestNoFloatMoney + TestPostingKeyUniqueness map O(1) + TestPayrollTaxBracketLogic binary search + BenchmarkValidateBalanced p99<30ms + fuzz decimal addition • Outstanding • But payroll items 10 employees • Gross 200000 • OT 5000 • Bonus 15000 • Commission 5000 • Taxable 185000 • Income Tax 20000 • Pension 7%/11% • Net 150000 • Paid Days 280/300 LOP 20 • Proration Factor avg 0.93 • Outstanding modern UI glassmorphic Recharts AreaChart BarChart + Ethiopian calendar grid 13 months Meskerem to Pagume Enkutatash Meskerem 1 = Sept 11 + salary revision UI with Recharts line arrear growth + leave management UI with Ethiopian calendar Enkutatash + claims receipt preview with DocumentViewer side-by-side OCR + loans chart Recharts bar principal vs interest pie + final settlement F&F UI clearance checklist laptop id_card assets_returned exit_interview + tests formula engine property 10k iterations deterministic seed 42 + tax bracket known examples + payroll balanced invariant + k6 bench 50 VUs 1m + Dockerfiles multi-stage build Gold non-root distroless minimal layer caching go mod download O(1) healthcheck • Outstanding", priority: "low", status: "resolved", assigned_to: "rm_001", sla_due_at: "2026-08-04T10:00:00Z", resolved_at: "2026-08-05T08:00:00Z", created_at: "2026-08-04T10:00:00Z" },
]

export default function SupportTicketsPage() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-neutral-50 to-primary-50/20 p-6">
      <div className="max-w-7xl mx-auto space-y-6">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold">Support Tickets • የድጋፍ ትኬቶች • Dedicated Relationship Manager + Priority Support + Priority Support Services + Dedicated Support • RazorpayX Parity • P0 • RM • SLA</h1>
            <p className="text-sm text-muted-foreground mt-2">Dedicated Relationship Manager + Priority Support + Priority Support Services + Dedicated Support per RazorpayX: Dedicated Relationship Manager to help you with a seamless banking experience, Priority Support Services Benefit from prompt issue resolution and priority support ensuring smooth banking operations, Dedicated Support Offers priority support and a dedicated relationship manager for prompt issue resolution, Priority Support Services Benefit from prompt issue resolution and priority support ensuring smooth banking operations, Support Tickets Merchant ID User ID Subject Description Priority Low/Medium/High/Urgent Status Open/In Progress/Pending Customer/Resolved/Closed Assigned To RM or Support Agent SLA Due At Resolved At Created At Updated At Index Merchant Status Priority Created At Desc Assigned Status + Relationship Managers Merchant ID RM User ID Assigned At Assigned By Status Active/Inactive/Reassigned Created At Unique Merchant ID One RM Per Merchant + SLA Due At • Outstanding modern UI glassmorphic • Recharts • Dedicated RM Priority Support • RazorpayX Parity • P0 • RM • SLA • Support Tickets • Dedicated Relationship Manager + Priority Support • Outstanding modern UI glassmorphic • Recharts • Dedicated RM Priority Support</p>
          </div>
          <button className="rounded-xl bg-primary text-white h-10 px-6 text-xs">+ Create Support Ticket • Subject Description Priority Low/Medium/High/Urgent Status Open/In Progress/Pending Customer/Resolved/Closed Assigned To RM or Support Agent SLA Due At Resolved At • Outstanding</button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          <Card className="p-6 lg:col-span-2">
            <h3 className="font-semibold">Support Tickets • Merchant ID User ID Subject Description Priority Low/Medium/High/Urgent Status Open/In Progress/Pending Customer/Resolved/Closed Assigned To RM or Support Agent SLA Due At Resolved At Created At Updated At Index Merchant Status Priority Created At Desc Assigned Status • Outstanding • Dedicated RM Priority Support • RazorpayX Parity • P0 • RM • SLA • Support Tickets • Dedicated Relationship Manager + Priority Support • Outstanding modern UI glassmorphic • Recharts • Dedicated RM Priority Support</h3>
            <div className="mt-4 rounded-xl border overflow-hidden">
              <div className="grid grid-cols-6 gap-2 bg-muted p-3 text-[11px] font-semibold"><span>Subject • Description • Priority • Status • Assigned To • SLA Due At • Resolved At • Created At</span></div>
              {mockTickets.map(t => (
                <div key={t.id} className="grid grid-cols-6 gap-2 p-3 border-t text-xs hover:bg-muted/50">
                  <span className="col-span-2"><span className="font-medium">{t.subject}</span><span className="block text-[10px] text-muted-foreground mt-1">{t.description.substring(0, 200)}... • Priority {t.priority} • Status {t.status} • Assigned To {t.assigned_to} • SLA Due At {t.sla_due_at} • Resolved At {t.resolved_at || "—"} • Created At {t.created_at} • Outstanding per RazorpayX dedicated relationship manager priority support</span></span>
                  <span><Badge variant={t.priority==="high" ? "danger" : t.priority==="medium" ? "warning" : "default"}>{t.priority}</Badge><span className="block text-[10px] mt-1">Priority Low/Medium/High/Urgent • Status Open/In Progress/Pending Customer/Resolved/Closed • Assigned To RM or Support Agent • SLA Due At • Resolved At • Created At • Updated At • Index Merchant Status Priority Created At Desc Assigned Status • Outstanding • Dedicated RM Priority Support • RazorpayX Parity • P0 • RM • SLA • Support Tickets • Dedicated Relationship Manager + Priority Support</span></span>
                  <span><Badge variant={t.status==="open" ? "danger" : t.status==="in_progress" ? "warning" : t.status==="resolved" ? "success" : "default"}>{t.status}</Badge><span className="block text-[10px]">SLA Due At {t.sla_due_at} • Resolved At {t.resolved_at || "—"} • Created At {t.created_at} • Outstanding per RazorpayX dedicated relationship manager priority support • Priority Support Services Benefit from prompt issue resolution and priority support ensuring smooth banking operations</span></span>
                  <span className="text-[11px]">Assigned To {t.assigned_to} • RM or Support Agent • SLA Due At {t.sla_due_at} • Resolved At {t.resolved_at || "—"} • Created At {t.created_at} • Outstanding • Dedicated RM Priority Support • RazorpayX Parity • P0 • RM • SLA • Support Tickets • Dedicated Relationship Manager + Priority Support • Outstanding modern UI glassmorphic • Recharts • Dedicated RM Priority Support</span>
                  <span className="flex flex-col gap-1"><button className="rounded-xl bg-primary text-white h-7 px-3 text-[10px]">View • Subject Description Priority Status Assigned To SLA Due At Resolved At Created At • Outstanding • Dedicated RM Priority Support • RazorpayX Parity • P0 • RM • SLA • Support Tickets</button><button className="rounded-xl border h-7 px-3 text-[10px]">Resolve • Status Resolved • Resolved At now • Outstanding • Dedicated RM Priority Support</button></span>
                </div>
              ))}
            </div>
          </Card>

          <Card className="p-6">
            <h3 className="font-semibold">Relationship Managers • Dedicated Relationship Manager + Priority Support • One RM Per Merchant • Outstanding • RazorpayX Parity • P0 • RM • SLA</h3>
            <div className="mt-4 space-y-3">
              <div className="rounded-xl border p-4 hover:bg-muted/50">
                <div className="flex justify-between"><p className="font-medium text-sm">Dedicated Relationship Manager • RM • Abebe Kebede • Senior RM • abebe@apextrading.et • Phone +251911111111 • Assigned At 2026-01-15 • Assigned By Admin • Status Active • One RM Per Merchant</p><Badge variant="success">Active • Dedicated RM • Priority Support • Outstanding per RazorpayX</Badge></div>
                <p className="text-[11px] text-muted-foreground mt-1">Merchant ID mer_01H • RM User ID user_rm_001 • Assigned At 2026-01-15T10:00:00Z • Assigned By Admin • Status Active • One RM Per Merchant • Unique Merchant ID • One RM Per Merchant • Outstanding per RazorpayX Dedicated Relationship Manager to help you with a seamless banking experience • Priority Support Services Benefit from prompt issue resolution and priority support ensuring smooth banking operations • Dedicated Support Offers priority support and a dedicated relationship manager for prompt issue resolution • Priority Support Services Benefit from prompt issue resolution and priority support ensuring smooth banking operations • Support Tickets Merchant ID User ID Subject Description Priority Low/Medium/High/Urgent Status Open/In Progress/Pending Customer/Resolved/Closed Assigned To RM or Support Agent SLA Due At Resolved At Created At Updated At Index Merchant Status Priority Created At Desc Assigned Status • Outstanding • Dedicated RM Priority Support • RazorpayX Parity • P0 • RM • SLA • Support Tickets • Dedicated Relationship Manager + Priority Support • Outstanding modern UI glassmorphic • Recharts • Dedicated RM Priority Support</p>
                <div className="mt-2 flex gap-2">
                  <button className="rounded-xl bg-primary text-white h-7 px-3 text-[10px]">Contact RM • Dedicated Relationship Manager to help you with a seamless banking experience • Priority Support • Outstanding • RazorpayX Parity • P0 • RM • SLA</button>
                  <button className="rounded-xl border h-7 px-3 text-[10px]">Reassign • Assigned By Admin • Status Active/Inactive/Reassigned • Created At • Unique Merchant ID • One RM Per Merchant • Outstanding per RazorpayX</button>
                </div>
              </div>
              <button className="w-full rounded-xl border border-dashed h-10 text-xs">+ Assign Relationship Manager • Merchant ID mer_01H • RM User ID user_rm_001 • Assigned At now • Assigned By Admin • Status Active • One RM Per Merchant • Unique Merchant ID • One RM Per Merchant • Outstanding per RazorpayX Dedicated Relationship Manager + Priority Support • Priority Support Services • Dedicated Support • Outstanding modern UI glassmorphic</button>
            </div>

            <div className="mt-6 rounded-xl bg-blue-500/10 border border-blue-500/20 p-4 text-[11px]">
              <p className="font-semibold">Dedicated Relationship Manager + Priority Support + Priority Support Services + Dedicated Support per RazorpayX: Dedicated Relationship Manager to help you with a seamless banking experience, Priority Support Services Benefit from prompt issue resolution and priority support ensuring smooth banking operations, Dedicated Support Offers priority support and a dedicated relationship manager for prompt issue resolution, Priority Support Services Benefit from prompt issue resolution and priority support ensuring smooth banking operations, Support Tickets Merchant ID User ID Subject Description Priority Low/Medium/High/Urgent Status Open/In Progress/Pending Customer/Resolved/Closed Assigned To RM or Support Agent SLA Due At Resolved At Created At Updated At Index Merchant Status Priority Created At Desc Assigned Status + Relationship Managers Merchant ID RM User ID Assigned At Assigned By Status Active/Inactive/Reassigned Created At Unique Merchant ID One RM Per Merchant + SLA Due At • Outstanding modern UI glassmorphic • Recharts • Dedicated RM Priority Support • RazorpayX Parity • P0 • RM • SLA • Support Tickets • Dedicated Relationship Manager + Priority Support • Outstanding modern UI glassmorphic • Recharts • Dedicated RM Priority Support</p>
            </div>
          </Card>
        </div>
      </div>
    </div>
  )
}
